### PR TITLE
Cloudevents dependency and up-l3 modules are now optional features

### PR DESCRIPTION
**Pull request by AnotherDaniel**
Re-created PR because of actions pipeline hiccup.

### CODE REVIEW

**Review by sophokles73 — COMMENTED** [review]
Can you also fix the spelling of the
> Upload coberage report

step names?

**Comment by PLeVasseur** [comment]
@AnotherDaniel:
Did we punt on testing the various combinations of features for now?

**Comment by AnotherDaniel** [comment]
It’s a cargo subcommand: https://github.com/frewsxcv/cargo-all-featuresOn 12. Mar 2024, at 19:37, Pete LeVasseur ***@***.***> wrote:﻿
@PLeVasseur commented on this pull request.



In .github/workflows/build.yaml:
>          run: |
-          # enable nightly features so that we can also include Doctests
-          RUSTC_BOOTSTRAP=1 cargo tarpaulin -o xml -o lcov -o html --doc --tests
+          cargo check-all-features
+      - name: cargo-test all possible feature combinations
+        run: |
+          cargo test-all-features

Ohhh nice. Is that this crate?

**Review by sophokles73 — APPROVED** [review]
LGTM

**Pull request merged**
