### PR TITLE
Fix function parameters of UTransport trait

### PR DESCRIPTION
**Pull request by sophokles73**
The documentation of the "send" function's parameters has been
adapted to match the semantics of the properties of UMessage.

### CODE REVIEW

**Review by stevenhartley — COMMENTED** [review]
hold off on this change as I work to fix the UTransport issue you've identified and we need to cleanup in core-api and all the language libraries.

**Comment by sophokles73** [comment]
@stevenhartley Can you create a new tag in the up-core-api repository once https://github.com/eclipse-uprotocol/up-core-api/pull/102 has been merged so that I can update this PR to pull in the changes from the protos?

**Review by stevenhartley — APPROVED** [review]

**Review by PLeVasseur — APPROVED** [review]
LGTM

**Comment by sophokles73** [comment]
@stevenhartley can you merge this?

**Pull request merged**
